[workspace]
authors = ["leonardo-kenny-isi <leonardo.treichel@senairs.org.br>"]
channels = ["conda-forge"]
name = "eramia-detr"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.0"

[dependencies]
transformers = ">=4.55.0,<5"
pillow = ">=11.3.0,<12"
cuda-version = "12.9.*"
pytorch-gpu = ">=2.7.1,<3"
jupyterlab = ">=4.4.5,<5"
label-studio-sdk = "==1.0.10"
python = "==3.12"
matplotlib = ">=3.10.5,<4"
torchmetrics = ">=1.8.0,<2"
tensorboardx = ">=2.6.2.2,<3"
accelerate = ">=0.26.0"
torchvision = ">=0.22.0,<0.23"
pycocotools = ">=2.0.10,<3"
pytorch-lightning = ">=2.5.2,<3"
albumentations = ">=2.0.8,<3"
tensorboard = ">=2.20.0,<3"
jupyter_console = ">=6.6.3,<7"
networkx = ">=3.5,<4"
tqdm = ">=4.67.1,<5"
ipywidgets = ">=8.1.7,<9"
timm = ">=1.0.19,<2"
evaluate = ">=0.4.5,<0.5"
scikit-learn = ">=1.7.1,<2"
cuda-toolkit = ">=12.9,<13"

[pypi-dependencies]
coco-eval = ">=0.0.4, <0.0.5"
ultralytics = ">=8.3.185, <9"

[tasks]
tensorboard = "tensorboard --logdir runs"
